Feature/search table
peterpep/FlowBaseUI pull request #10
Opened 2017-10-26 03:11 UTC by peterpep

added autocomplete search

2017-10-29 05:01 UTC, bry-guy requested changes
such code
many wow
very vue

2017-10-29 05:01 UTC, bry-guy commented on src/components/Overview.vue
> +<template>
move 'pages' to src/pages
- src/pages/chemicals/details (this is currently called 'overview')

leave shared components (such as dynamic table) in src/components

2017-10-29 05:01 UTC, bryansmi commented on src/components/Overview.vue
> +    <SearchTable :rows="this.$store.getters.chemicals" :columnNames="columns" @filterData="setData"></SearchTable>
rename searcher

2017-10-29 05:01 UTC, bryansmi commented on src/components/Overview.vue
> +    this.dataForTable = this.$store.getters.chemicals;
rename dataForTable to dynamicTableDataSource

2017-10-29 05:01 UTC, bryansmi commented on src/components/SearchTable.vue
> +    <form @submit.prevent="$emit('filterData',searchJsonData(rows, searchIn, searchTerm))">
change filterData to submitClicked

2017-10-29 05:01 UTC, bryansmi commented on src/components/Overview.vue
> +    <SearchTable :rows="this.$store.getters.chemicals" :columnNames="columns" @filterData="setData"></SearchTable>
rename filterData to 'submitClicked'
rename 'setData' to 'handleSubmitClicked'

2017-10-29 05:01 UTC, bryansmi commented on src/components/Overview.vue
> +    setData: function(e) {
rename 'e' to 'filteredData'

2017-10-29 05:01 UTC, bryansmi commented on src/components/SearchTable.vue
> +        <select class="dropDownEdges" v-model="searchIn">
rename 'searchIn' to 'searchBy'

2017-10-29 05:01 UTC, bryansmi commented on src/components/SearchTable.vue
> +            formatColumn: function(name) {
Make global helper function named 'splitOnUnderscores'

2017-10-29 05:01 UTC, bryansmi commented on src/vuex/models/chemicals.js
> +    USER_OBJECT
rename USER_OBJECT to CHEMICAL_COLLECTION

2017-10-29 12:05 UTC, peterpep commented
completed PR requested changes as well as removing the expiration status row highlighting from DynamicTable and moving into scoped slot (methods for binding class moved into mixin)

2017-10-30 06:35 UTC, bry-guy approved these changes

2017-10-30 06:36 UTC, merged